#!/bin/sh

INPUT=$1
OUTPUT=$2

CONVERT="convert"

if test "`which gm`" != ""
then
    CONVERT="gm convert"
fi

${CONVERT} -unsharp 1.5x1.5 -modulate 175,150 -contrast -contrast -contrast ${INPUT} ${OUTPUT}

${CONVERT} -gaussian 1x2 ${OUTPUT} ${OUTPUT}
