#!/bin/sh

INPUT=$1
OUTPUT=$2

PYTHON=`which python`

WHOAMI=`$PYTHON -c 'import os, sys; print os.path.realpath(sys.argv[1])' $0`

WHEREAMI=`dirname $WHOAMI`
FILTR=`dirname $WHEREAMI`

${PYTHON} ${FILTR}/utils/dither.py ${INPUT} ${OUTPUT}
