#!/bin/sh

INPUT1=$1
INPUT2=$2
FILTR1=$3
FILTR2=$4
OUTPUT=$5

# FIX ME: do absrealpath dance

if test $OSTYPE = "FreeBSD"
then
    WHOAMI=`realpath $0`
elif [[ $OSTYPE == darwin* ]]
then
    WHOAMI=`python -c 'import os, sys; print os.path.realpath(sys.argv[1])' $0`
else
    WHOAMI=`readlink -f $0`    
fi

RECIPES=`dirname $WHOAMI`
UTILS=`dirname $RECIPES`/utils

CONVERT="convert"
COMPOSITE="composite"
IDENTIFY="identify"

if test "`which gm`" != ""
then
    CONVERT="gm convert"
    COMPOSITE="gm composite"
    IDENTIFY="gm identify"
fi

TMP=`mktemp -d -t stndpip-`

FILTR_UID=`${UTILS}/md5sum ${INPUT1}`

ID="${TMP}/${FILTR_UID}-id.txt"

TMP1="${TMP}/${FILTR_UID}-tmp.jpg"
TMP2="${TMP}/${FILTR_UID}-tmp2.jpg"

CROP1="${TMP}/${FILTR_UID}-crop.jpg"
CROP2="${TMP}/${FILTR_UID}-crop2.jpg"

# TO DO: check FILTR1/2 here...

# Run the filters

${RECIPES}/${FILTR1} ${INPUT1} ${TMP1}
${RECIPES}/${FILTR2} ${INPUT2} ${TMP2}

# Crop the images

for img in ${TMP1} ${TMP2}
do

    ${IDENTIFY} ${img} | awk '{ split($3,a,"+"); print a[1]; }' > ${ID}
    W_IMG=`awk '{ split($1, dims,"x"); print dims[1]; }' ${ID}`
    H_IMG=`awk '{ split($1, dims,"x"); print dims[2]; }' ${ID}`

    echo "[heathr] img dimensions : ${W_IMG} x ${H_IMG}"
          
    CROP_TO=${W_IMG}
    CROP_X=`awk "BEGIN { print ${W_IMG} - ${H_IMG} }"`
    CROP_Y=0
          
    if [ ${W_IMG} -gt ${H_IMG} ]
    then
        CROP_TO=${H_IMG}
        CROP_Y=`awk "BEGIN { print ${H_IMG} - ${W_IMG} }"`
        CROP_X=0
    fi
    
    echo "[heathr] ${CONVERT} -crop ${CROP_TO}x${CROP_TO}+${CROP_X}+${CROP_Y} ${img} ${img}"
    ${CONVERT} -crop ${CROP_TO}x${CROP_TO}+${CROP_X}+${CROP_Y} ${img} ${img}

    echo "[heathr] ${IDENTIFY} ${img}"

    ${IDENTIFY} ${img}  | awk '{ split($3,a,"+"); print a[1]; }' > ${ID}
    W_IMG=`awk '{ split($1, dims,"x"); print dims[1]; }' ${ID}`
    H_IMG=`awk '{ split($1, dims,"x"); print dims[2]; }' ${ID}`

    BORDER_SIDES=`awk "BEGIN { print ${W_IMG} * .1 }"`
    BORDER_TOP=`awk "BEGIN { print ${H_IMG} * .1 }"`
    BORDER_BOTTOM=`awk "BEGIN { print ${H_IMG} * .3 }"`

    echo "[${FILTER}][heathr] img borders ${BORDER_SIDES} ; ${BORDER_TOP} ; ${BORDER_BOTTOM}"
          
    W_CANVAS=`awk "BEGIN { print ${W_IMG} + (${BORDER_SIDES} * 2) }"`
    H_CANVAS=`awk "BEGIN { print ${BORDER_TOP} + ${H_IMG} + ${BORDER_BOTTOM} }"`
          
    echo "[heathr] img canvas ${W_CANVAS} x ${H_CANVAS}"
          
    CANVAS=${TMP}/${FILTR_UID}-blank.jpg
    BG=${TMP}/${FILTR_UID}-bg.jpg
    DRAFT=${TMP}/${FILTR_UID}-draft.jpg
          
    echo "[heathr] ${CONVERT} -size ${W_CANVAS}x${H_CANVAS} xc:white ${CANVAS}"
    ${CONVERT} -size ${W_CANVAS}x${H_CANVAS} xc:white ${CANVAS}
          
    # composite
          
    echo "[heathr] ${COMPOSITE} -geometry +${BORDER_SIDES}+${BORDER_TOP} ${img} ${CANVAS} ${DRAFT}"
    ${COMPOSITE} -geometry +${BORDER_SIDES}+${BORDER_TOP} ${img} ${CANVAS} ${DRAFT}

    # generate the background
          
    W_BG=`awk "BEGIN { print ${W_CANVAS} + 2 }"`
    H_BG=`awk "BEGIN { print ${H_CANVAS} + 2 }"`

    echo "[heathr] ${CONVERT} -size ${W_BG}x${H_BG} xc:black ${BG}"
    ${CONVERT} -size ${W_BG}x${H_BG} xc:black ${BG}
          
    # place the composite on the background
          
    echo "[heathr] ${COMPOSITE} -geometry +1+1 ${DRAFT} ${BG} ${img}"
    ${COMPOSITE} -geometry +1+1 ${DRAFT} ${BG} ${img}         
          
    rm -f ${ID}
    rm -f ${DRAFT}
    rm -f ${CANVAS}
    rm -f ${BG}

    echo "[heathr] polaroid ${img}"

done

echo "DONE"
