#!/bin/sh

INPUT1=$1
INPUT2=$2
FILTR1=$3
FILTR2=$4
OUTPUT=$5

# FIX ME: do absrealpath dance

WHOAMI=$0 
RECIPES=`dirname $WHOAMI`
UTILS=`dirname $RECIPES`/utils

CONVERT="convert"
COMPOSITE="composite"
IDENTIFY="identify"

if test "`which gm`" != ""
then
    CONVERT="gm convert"
    COMPOSITE="gm composite"
    IDENTIFY="gm identify"
fi

TMP=`mktemp -d -t stndpip-`
FILTR_UID=`${UTILS}/md5sum ${INPUT1}`

ID="${TMP}/${FILTR_UID}-id.txt"

TMP1="${TMP}/${FILTR_UID}-tmp.jpg"
TMP2="${TMP}/${FILTR_UID}-tmp2.jpg"

CROP1="${TMP}/${FILTR_UID}-crop.jpg"
CROP2="${TMP}/${FILTR_UID}-crop2.jpg"

# TO DO: check FILTR1/2 here...

# Run the filters

echo "${RECIPES}/${FILTR1} ${INPUT1} ${TMP1}"
echo "${RECIPES}/${FILTR2} ${INPUT2} ${TMP2}"

exit

# Crop the images

for img in ${TMP1} ${TMP2}
do

    ${IDENTIFY} ${img} | awk '{ split($3,a,"+"); print a[1]; }' > ${ID}
    W_IMG=`awk '{ split($1, dims,"x"); print dims[1]; }' ${ID}`
    H_IMG=`awk '{ split($1, dims,"x"); print dims[2]; }' ${ID}`

    echo "[heathr] img dimensions : ${W_IMG} x ${H_IMG}"
          
    CROP_TO=${W_IMG}
    CROP_X=`awk "BEGIN { print ${W_IMG} - ${H_IMG} }"`
    CROP_Y=0
          
    if [${W_IMG} -gt ${H_IMG}]
    then
        CROP_TO=${H_IMG}
        CROP_Y=`awk "BEGIN { print ${H_IMG} - ${W_IMG} }"`
        CROP_X=0
    fi

    echo "[heathr] ${CONVERT} -crop ${CROP_TO}x${CROP_TO}+${CROP_X}+${CROP_Y} ${img} ${img}"
    ${CONVERT} -crop ${CROP_TO}x${CROP_TO}+${CROP_X}+${CROP_Y} ${img} ${img}

    echo "[heathr] ${IDENTIFY} ${img}"
    # /heathr
    fi
done

echo "DONE"
