#!/bin/sh

INPUT1=$1
INPUT2=$2
FILTR1=$3
FILTR2=$4
OUTPUT=$5

if test $OSTYPE = "FreeBSD"
then
    WHOAMI=`realpath $0`
elif [[ $OSTYPE == darwin* ]]
then
    WHOAMI=`python -c 'import os, sys; print os.path.realpath(sys.argv[1])' $0`
else
    WHOAMI=`readlink -f $0`    
fi

FILTR=`basename $WHOAMI`
RECIPES=`dirname $WHOAMI`
UTILS=`dirname $RECIPES`/utils

CONVERT="convert"
COMPOSITE="composite"
IDENTIFY="identify"

if test "`which gm`" != ""
then
    CONVERT="gm convert"
    COMPOSITE="gm composite"
    IDENTIFY="gm identify"
fi

for f in ${FILTR1} ${FILTR2}
do
    if [ ! -f ${RECIPES}/${f} ]
    then
	echo "[${FILTR}] unknown filtr '${f}', exiting"
	exit
    fi
done

# Set up

TMP=`mktemp -d -t heathr-`

FILTR_UID=`${UTILS}/md5sum ${INPUT1}`

ID="${TMP}/${FILTR_UID}-id.txt"
TMP1="${TMP}/${FILTR_UID}-tmp.jpg"
TMP2="${TMP}/${FILTR_UID}-tmp2.jpg"

# Run the filters

echo "[${FILTR}] filtr ${INPUT1} w/ ${FILTR1}"
${RECIPES}/${FILTR1} ${INPUT1} ${TMP1}

echo "[${FILTR}] filtr ${INPUT2} w/ ${FILTR2}"
${RECIPES}/${FILTR2} ${INPUT2} ${TMP2}

# Crop the images

for img in ${TMP1} ${TMP2}
do

    echo "[${FILTR}] filtr ${img} w/ edwn"    
    ${RECIPES}/edwn ${img} ${img}

done

echo "[${FILTR}] combine w/ stndpipe"  

${RECIPES}/stndpipe ${TMP1} ${TMP2} ${OUTPUT}

rm -f ${TMP1}
rm -f ${TMP2}

echo "[${FILTR}] done"
exit
