#!/bin/sh

INPUT=$1
OUTPUT=$2

if test $OSTYPE = "FreeBSD"
then
    WHOAMI=`realpath $0`
elif test $OSTYPE = darwin*
then
    WHOAMI=`python -c 'import os, sys; print os.path.realpath(sys.argv[1])' $0`
else
    WHOAMI=`readlink -f $0`    
fi

FILTR=`basename $WHOAMI`
RECIPES=`dirname $WHOAMI`

COMPOSITE="composite"

if test "`which gm`" != ""
then
    COMPOSITE="gm composite"
fi

${RECIPES}/postcrd ${INPUT} ${OUTPUT}

${COMPOSITE} -compose multiply ${INPUT} ${OUTPUT} ${OUTPUT}
