#!/bin/sh

INPUT=$1
OUTPUT=$2

if test $OSTYPE = "FreeBSD"
then
    WHOAMI=`realpath $0`
elif test $OSTYPE = "darwin"
then
    WHOAMI=`python -c 'import os, sys; print os.path.realpath(sys.argv[1])' $0`
else
    WHOAMI=`readlink -f $0`    
fi

FILTR=`basename $WHOAMI`
RECIPES=`dirname $WHOAMI`
UTILS=`dirname $RECIPES`/utils

CONVERT="convert"
COMPOSITE="composite"
IDENTIFY="identify"

if test "`which gm`" != ""
then
    CONVERT="gm convert"
    COMPOSITE="gm composite"
    IDENTIFY="gm identify"
fi

if test $OSTYPE = linux
then
    TMP=`mktemp -d -t ${FILTR}-XXXXX-`
else
    TMP=`mktemp -d -t $FILTR-`
fi

FILTR_UID=`${UTILS}/md5sum ${INPUT}`

ID="${TMP}/${FILTR_UID}-id.txt"
LOMO="${TMP}/${FILTR_UID}-lomo.png"
MASK="${TMP}/${FILTR_UID}-mask.png"

${IDENTIFY} ${INPUT}  | awk '{ split($3,a,"+"); print a[1]; }' > ${ID}

W_ORIG=`awk '{ split($1, dims,"x"); print dims[1]; }' ${ID}`
H_ORIG=`awk '{ split($1, dims,"x"); print dims[2]; }' ${ID}`

W_THUMB=`awk '{ split($1, dims,"x"); print dims[1] / 10; }' ${ID}`
H_THUMB=`awk '{ split($1, dims,"x"); print dims[2] / 10; }' ${ID}`

${CONVERT} -size ${W_THUMB}x${H_THUMB} -contrast -modulate 100,150 -gaussian 1x2 +matte ${INPUT} ${MASK}

${CONVERT} -resize ${W_ORIG}x${H_ORIG} -gaussian 0x5 -modulate 180,150 ${MASK} ${MASK}

${CONVERT} -unsharp 1.5x1.5 -modulate 175,100 -contrast -contrast -contrast ${INPUT} ${LOMO}

${CONVERT} -gaussian 1x2 ${LOMO} ${LOMO}

${COMPOSITE} -compose multiply ${MASK} ${LOMO} ${OUTPUT}

rm -f ${ID}
rm -f ${LOMO}
rm -f ${MASK} 
