#!/bin/sh

INPUT=$1
OUTPUT=$2

PYTHON=`which python`

WHOAMI=`$PYTHON -c 'import os, sys; print os.path.realpath(sys.argv[1])' $0`

FILTR=`basename $WHOAMI`
RECIPES=`dirname $WHOAMI`
UTILS=`dirname $RECIPES`/utils

${PYTHON} ${UTILS}/triangulizor.py -f JPEG ${INPUT} ${OUTPUT}

echo "[${FILTR}] done"
exit
