#!/bin/sh

INPUT=$1
OUTPUT=$2

PYTHON=`which python`

if test $OSTYPE = "FreeBSD"
then
    WHOAMI=`realpath $0`
elif test $OSTYPE = darwin*
then
    WHOAMI=`$PYTHON -c 'import os, sys; print os.path.realpath(sys.argv[1])' $0`
else
    WHOAMI=`readlink -f $0`
fi

FILTR=`basename $WHOAMI`
RECIPES=`dirname $WHOAMI`
UTILS=`dirname $RECIPES`/utils

${PYTHON} ${UTILS}/triangulizor.py -f JPEG ${INPUT} ${OUTPUT}

echo "[${FILTR}] done"
exit
