#!/bin/sh

INPUT1=$1
INPUT2=$2
OUTPUT=$3

if test $OSTYPE = "FreeBSD"
then
    WHOAMI=`realpath $0`
elif test $OSTYPE = darwin* 
then
    WHOAMI=`python -c 'import os, sys; print os.path.realpath(sys.argv[1])' $0`
else
    WHOAMI=`readlink -f $0`    
fi

FILTR=`basename $WHOAMI`
RECIPES=`dirname $WHOAMI`
UTILS=`dirname $RECIPES`/utils

CONVERT="convert"
COMPOSITE="composite"
IDENTIFY="identify"

if test "`which gm`" != ""
then
    CONVERT="gm convert"
    COMPOSITE="gm composite"
    IDENTIFY="gm identify"
fi

if test $OSTYPE = linux
then
    TMP=`mktemp -d -t ${FILTR}-XXXXX-`
else
    TMP=`mktemp -d -t $FILTR-`
fi

FILTR_UID=`${UTILS}/md5sum ${INPUT1}`

ID1="${TMP}/${FILTR_UID}-id.txt"
ID2="${TMP}/${FILTR_UID}-id2.txt"

CANVAS=${TMP}/${FILTR_UID}-blank.png
DRAFT=${TMP}/${FILTR_UID}-draft.png

${IDENTIFY} ${INPUT1}  | awk '{ split($3,a,"+"); print a[1]; }' > ${ID1}
W_ORIG=`awk '{ split($1, dims,"x"); print dims[1]; }' ${ID1}`
H_ORIG=`awk '{ split($1, dims,"x"); print dims[2]; }' ${ID1}`

${IDENTIFY} ${INPUT2} | awk '{ split($3,a,"+"); print a[1]; }' > ${ID2}
W_ORIG2=`awk '{ split($1, dims,"x"); print dims[1]; }' ${ID2}`
H_ORIG2=`awk '{ split($1, dims,"x"); print dims[2]; }' ${ID2}`

echo "[${FILTR}] dimensions : ${W_ORIG2} x ${H_ORIG2}"

W_NEW=`awk "BEGIN{ print ${W_ORIG}+${W_ORIG2} }"`
H_NEW=${H_ORIG}

if [ ${H_ORIG2} -gt ${H_ORIG} ]
then
    H_NEW=${H_ORIG2}
fi 

echo "[${FILTR}] dimensions : ${W_NEW} x ${H_NEW}"

BORDER_CALC=${W_NEW}
echo "[${FILTR}] border calc : ${BORDER_CALC}"

if [ ${H_NEW} -gt ${W_NEW} ]
then
    BORDER_CALC=${H_NEW}
    echo "[${FILTR}] border calc reset : ${BORDER_CALC}"
fi 

BORDER_SIDES=0  #`awk "BEGIN { print ${BORDER_CALC} * .1 }"`
BORDER_CENTER=`awk "BEGIN { print ${BORDER_CALC} * .005 }"`
BORDER_TOP=0    #`awk "BEGIN { print ${BORDER_CALC} * .1 }"`
BORDER_BOTTOM=0 #`awk "BEGIN { print ${BORDER_CALC} * .15 }"`

echo "[${FILTR}] borders ${BORDER_SIDES} ; ${BORDER_CENTER} ; ${BORDER_TOP} ; ${BORDER_BOTTOM}"

W_CANVAS=`awk "BEGIN { print ${W_NEW} + (${BORDER_SIDES} * 2) + ${BORDER_CENTER} }"`
H_CANVAS=`awk "BEGIN { print ${BORDER_TOP} + ${H_NEW} + ${BORDER_BOTTOM} }"`

echo "[${FILTR}] make canvas ({$CANVAS}) ${W_CANVAS} x ${H_CANVAS}"

if [ `echo $OUTPUT | awk '/png$/ {print "PNG"}'` ]
then
    echo "[${FILTR}] create canvas with transparent background"
    ${CONVERT} -size ${W_CANVAS}x${H_CANVAS} xc:none ${CANVAS}
else
    ${CONVERT} -size ${W_CANVAS}x${H_CANVAS} xc:white ${CANVAS}
fi


W_OFFSET=`awk "BEGIN { print ${W_ORIG} + ${BORDER_SIDES} + ${BORDER_CENTER} }"`

echo "[${FILTR}] ${COMPOSITE} -geometry +${BORDER_SIDES}+${BORDER_TOP} ${INPUT1} ${CANVAS} ${DRAFT}"
${COMPOSITE} -quality 100 -geometry +${BORDER_SIDES}+${BORDER_TOP} ${INPUT1} ${CANVAS} ${DRAFT}

echo "[${FILTR}] ${COMPOSITE} -geometry +${W_OFFSET}+${BORDER_TOP} ${INPUT2} ${DRAFT} ${OUTPUT}"
${COMPOSITE} -quality 100 -geometry +${W_OFFSET}+${BORDER_TOP} ${INPUT2} ${DRAFT} ${OUTPUT}

rm -f ${ID}
rm -f ${ID2}
rm -f ${CANVAS}
rm -f ${DRAFT}

echo "[${FILTR}] done"
exit
