#!/bin/sh

FILTER='dithr'

INPUT=$1
OUTPUT=$2

PYTHON=`which python`

if test $OSTYPE = "FreeBSD"
then
    WHOAMI=`realpath $0`
elif test $OSTYPE = "darwin"
then
    WHOAMI=`$PYTHON -c 'import os, sys; print os.path.realpath(sys.argv[1])' $0`
else
    WHOAMI=`readlink -f $0`
fi

WHEREAMI=`dirname $WHOAMI`

${PYTHON} ${WHEREAMI}/dither.py ${INPUT} ${OUTPUT}
